name: Release
on:
  push:
    branches:
      - 'main'
      - 'next_major'
jobs:
  release:
    name: Final
    if: ${{ github.repository == 'primer/css' && github.ref_name == 'main' }}
    uses: primer/.github/.github/workflows/release.yml@main
    secrets:
      gh_token: ${{ secrets.GPR_AUTH_TOKEN_SHARED }}
      npm_token: ${{ secrets.NPM_AUTH_TOKEN_SHARED }}
